package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gustavo/emerald/models"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Cliente)
// DB Table: Plural (clientes)
// Resource: Plural (Clientes)
// Path: Plural (/clientes)
// View Template Folder: Plural (/templates/clientes/)

// ClientesResource is the resource for the Cliente model
type ClientesResource struct {
	buffalo.Resource
}

// List gets all Clientes. This function is mapped to the path
// GET /clientes
func (v ClientesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	clientes := &models.Clientes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Clientes from the DB
	if err := q.All(clientes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(clientes))
}

// Show gets the data for one Cliente. This function is mapped to
// the path GET /clientes/{cliente_id}
func (v ClientesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cliente
	cliente := &models.Cliente{}

	// To find the Cliente the parameter cliente_id is used.
	if err := tx.Find(cliente, c.Param("cliente_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(cliente))
}

// New default implementation. Returns a 404
func (v ClientesResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Cliente to the DB. This function is mapped to the
// path POST /clientes
func (v ClientesResource) Create(c buffalo.Context) error {
	// Allocate an empty Cliente
	cliente := &models.Cliente{}

	// Bind cliente to the html form elements
	if err := c.Bind(cliente); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(cliente)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(cliente))
}

// Edit default implementation. Returns a 404
func (v ClientesResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Cliente in the DB. This function is mapped to
// the path PUT /clientes/{cliente_id}
func (v ClientesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cliente
	cliente := &models.Cliente{}

	if err := tx.Find(cliente, c.Param("cliente_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Cliente to the html form elements
	if err := c.Bind(cliente); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(cliente)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(cliente))
}

// Destroy deletes a Cliente from the DB. This function is mapped
// to the path DELETE /clientes/{cliente_id}
func (v ClientesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Cliente
	cliente := &models.Cliente{}

	// To find the Cliente the parameter cliente_id is used.
	if err := tx.Find(cliente, c.Param("cliente_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(cliente); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(cliente))
}
