package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gustavo/emerald/models"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
	"github.com/satori/go.uuid"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Contrato)
// DB Table: Plural (contratos)
// Resource: Plural (Contratos)
// Path: Plural (/contratos)
// View Template Folder: Plural (/templates/contratos/)

// ContratosResource is the resource for the Contrato model
type ContratosResource struct {
	buffalo.Resource
}

// List gets all Contratos. This function is mapped to the path
// GET /contratos
func (v ContratosResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	contratos := &models.Contratos{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Contratos from the DB
	if err := q.All(contratos); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(contratos))
}

// Show gets the data for one Contrato. This function is mapped to
// the path GET /contratos/{contrato_id}
func (v ContratosResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Contrato
	contrato := &models.Contrato{}

	// To find the Contrato the parameter contrato_id is used.
	if err := tx.Find(contrato, c.Param("contrato_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(contrato))
}

// New default implementation. Returns a 404
func (v ContratosResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Contrato to the DB. This function is mapped to the
// path POST /contratos
func (v ContratosResource) Create(c buffalo.Context) error {
	// Allocate an empty Contrato
	contrato := &models.Contrato{}

	// Bind contrato to the html form elements
	if err := c.Bind(contrato); err != nil {
		return errors.WithStack(err)
	}

	// Get ClienteID from param
	cliID, err := uuid.FromString(c.Param("cliente_id"))
	if err != nil {
		return errors.WithStack(errors.New("no cliente found"))
	}
	contrato.ClienteID = cliID

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(contrato)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(contrato))
}

// Edit default implementation. Returns a 404
func (v ContratosResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Contrato in the DB. This function is mapped to
// the path PUT /contratos/{contrato_id}
func (v ContratosResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Contrato
	contrato := &models.Contrato{}

	if err := tx.Find(contrato, c.Param("contrato_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Contrato to the html form elements
	if err := c.Bind(contrato); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(contrato)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(contrato))
}

// Destroy deletes a Contrato from the DB. This function is mapped
// to the path DELETE /contratos/{contrato_id}
func (v ContratosResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Contrato
	contrato := &models.Contrato{}

	// To find the Contrato the parameter contrato_id is used.
	if err := tx.Find(contrato, c.Param("contrato_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(contrato); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(contrato))
}
