package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gustavo/emerald/models"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Escola)
// DB Table: Plural (escolas)
// Resource: Plural (Escolas)
// Path: Plural (/escolas)
// View Template Folder: Plural (/templates/escolas/)

// EscolasResource is the resource for the Escola model
type EscolasResource struct {
	buffalo.Resource
}

// List gets all Escolas. This function is mapped to the path
// GET /escolas
func (v EscolasResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	escolas := &models.Escolas{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Escolas from the DB
	if err := q.All(escolas); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(escolas))
}

// Show gets the data for one Escola. This function is mapped to
// the path GET /escolas/{escola_id}
func (v EscolasResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Escola
	escola := &models.Escola{}

	// To find the Escola the parameter escola_id is used.
	if err := tx.Find(escola, c.Param("escola_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(escola))
}

// New default implementation. Returns a 404
func (v EscolasResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Escola to the DB. This function is mapped to the
// path POST /escolas
func (v EscolasResource) Create(c buffalo.Context) error {
	// Allocate an empty Escola
	escola := &models.Escola{}

	// Bind escola to the html form elements
	if err := c.Bind(escola); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(escola)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(escola))
}

// Edit default implementation. Returns a 404
func (v EscolasResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Escola in the DB. This function is mapped to
// the path PUT /escolas/{escola_id}
func (v EscolasResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Escola
	escola := &models.Escola{}

	if err := tx.Find(escola, c.Param("escola_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Escola to the html form elements
	if err := c.Bind(escola); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(escola)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(escola))
}

// Destroy deletes a Escola from the DB. This function is mapped
// to the path DELETE /escolas/{escola_id}
func (v EscolasResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Escola
	escola := &models.Escola{}

	// To find the Escola the parameter escola_id is used.
	if err := tx.Find(escola, c.Param("escola_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(escola); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(escola))
}
