package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gustavo/emerald/models"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
	"github.com/satori/go.uuid"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Filho)
// DB Table: Plural (filhos)
// Resource: Plural (Filhos)
// Path: Plural (/filhos)
// View Template Folder: Plural (/templates/filhos/)

// FilhosResource is the resource for the Filho model
type FilhosResource struct {
	buffalo.Resource
}

// List gets all Filhos. This function is mapped to the path
// GET /filhos
func (v FilhosResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	filhos := &models.Filhos{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Filhos from the DB
	if err := q.All(filhos); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(filhos))
}

// Show gets the data for one Filho. This function is mapped to
// the path GET /filhos/{filho_id}
func (v FilhosResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Filho
	filho := &models.Filho{}

	// To find the Filho the parameter filho_id is used.
	if err := tx.Find(filho, c.Param("filho_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(filho))
}

// New default implementation. Returns a 404
func (v FilhosResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Filho to the DB. This function is mapped to the
// path POST /filhos
func (v FilhosResource) Create(c buffalo.Context) error {
	// Allocate an empty Filho
	filho := &models.Filho{}

	// Bind filho to the html form elements
	if err := c.Bind(filho); err != nil {
		return errors.WithStack(err)
	}

	cliID, err := uuid.FromString(c.Param("cliente_id"))
	if err != nil {
		return errors.WithStack(errors.New("no cliente found"))
	}

	filho.ClienteID = cliID

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(filho)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(filho))
}

// Edit default implementation. Returns a 404
func (v FilhosResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Filho in the DB. This function is mapped to
// the path PUT /filhos/{filho_id}
func (v FilhosResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Filho
	filho := &models.Filho{}

	if err := tx.Find(filho, c.Param("filho_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Filho to the html form elements
	if err := c.Bind(filho); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(filho)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(filho))
}

// Destroy deletes a Filho from the DB. This function is mapped
// to the path DELETE /filhos/{filho_id}
func (v FilhosResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Filho
	filho := &models.Filho{}

	// To find the Filho the parameter filho_id is used.
	if err := tx.Find(filho, c.Param("filho_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(filho); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(filho))
}
