package actions

import (
	"github.com/gustavo/emerald/models"

	"github.com/gobuffalo/buffalo"
	"github.com/markbates/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Pagamento)
// DB Table: Plural (pagamentos)
// Resource: Plural (Pagamentos)
// Path: Plural (/pagamentos)
// View Template Folder: Plural (/templates/pagamentos/)

// PagamentosResource is the resource for the Pagamento model
type PagamentosResource struct {
	buffalo.Resource
}

// List gets all Pagamentos. This function is mapped to the path
// GET /pagamentos
func (v PagamentosResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	pagamentos := &models.Pagamentos{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Pagamentos from the DB
	if err := q.All(pagamentos); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the headers so clients know how to paginate.
	c.Response().Header().Set("X-Pagination", q.Paginator.String())

	return c.Render(200, r.JSON(pagamentos))
}

// Show gets the data for one Pagamento. This function is mapped to
// the path GET /pagamentos/{pagamento_id}
func (v PagamentosResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pagamento
	pagamento := &models.Pagamento{}

	// To find the Pagamento the parameter pagamento_id is used.
	if err := tx.Find(pagamento, c.Param("pagamento_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.JSON(pagamento))
}

// New default implementation. Returns a 404
func (v PagamentosResource) New(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Create adds a Pagamento to the DB. This function is mapped to the
// path POST /pagamentos
func (v PagamentosResource) Create(c buffalo.Context) error {
	// Allocate an empty Pagamento
	pagamento := &models.Pagamento{}

	// Bind pagamento to the html form elements
	if err := c.Bind(pagamento); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pagamento)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(201, r.JSON(pagamento))
}

// Edit default implementation. Returns a 404
func (v PagamentosResource) Edit(c buffalo.Context) error {
	return c.Error(404, errors.New("not available"))
}

// Update changes a Pagamento in the DB. This function is mapped to
// the path PUT /pagamentos/{pagamento_id}
func (v PagamentosResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pagamento
	pagamento := &models.Pagamento{}

	if err := tx.Find(pagamento, c.Param("pagamento_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Pagamento to the html form elements
	if err := c.Bind(pagamento); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(pagamento)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Render errors as JSON
		return c.Render(400, r.JSON(verrs))
	}

	return c.Render(200, r.JSON(pagamento))
}

// Destroy deletes a Pagamento from the DB. This function is mapped
// to the path DELETE /pagamentos/{pagamento_id}
func (v PagamentosResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pagamento
	pagamento := &models.Pagamento{}

	// To find the Pagamento the parameter pagamento_id is used.
	if err := tx.Find(pagamento, c.Param("pagamento_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(pagamento); err != nil {
		return errors.WithStack(err)
	}

	return c.Render(200, r.JSON(pagamento))
}
